### ISSUE TITLE
Working example for SMPTE2022-1 FEC live-streaming with Raspberry Pis and Auvidea B101-HDMI-Input

### ISSUE THREAD

**Issue by wetterfrosch** [MathieuDuponchelle/MathieuDuponchelle.github.io#12]
... including audio and HDMI-loop-out. Freshly tested with Raspberry Pi 4B+ devices on Raspberry Pi OS 2023-10-10 Bookworm in March 2024, two example gst-launch1.0 pipelines: https://c3voc.de/wiki/hardware:video-pis

This issue is meant as a JFYI and shall be solved by itself.

**Comment by MathieuDuponchelle** [comment]
thanks :)
