### ISSUE TITLE
FEC Issues with H265 Encoding

### ISSUE THREAD

**Issue by krishnarao21** [MathieuDuponchelle/MathieuDuponchelle.github.io#8]
Hi 
i am trying to integrate the FEC feature in our application. Verified the feature with H264 encoding, but with H265 it is not working. Receiver side, added netsim element to check the behaviour. If I encode with H264, it is working properly. With H265 encoding, observed the packet drops. Please let me know any inputs on this issue. I am using 1.20 gstreamer.

**Comment by MathieuDuponchelle** [comment]
Hey, this should be filed against gstreamer's gitlab https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues :) You'll also want to provide more specific steps to reproduce the issue you're seeing.
